### ISSUE TITLE
Request can not be processed without authentication

### ISSUE THREAD

**Issue by yageek** [RecastAI/SDK-Golang#10]
By using the provided code example, I have this error each time I want to send a request:
```
Request can not be processed without authentication
```

The sample code:
```go
package main

import (
	"fmt"
	"github.com/RecastAI/SDK-Golang/recast"
	"net/http"
)

func bot(w http.ResponseWriter, r *http.Request) {
	fmt.Println("Message received")
	message, err := recast.ParseConnectorMessage(r)
	if err != nil {
		fmt.Println("Error decoding message")
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	reply := recast.NewTextMessage("Hello, world!")

	client := recast.ConnectClient{Token: "CONNECTOR_TOKEN"}

	// Reply to the incoming message through BotConnector API
	err = client.SendMessage(message.ConversationId, reply)
	if err != nil {
		fmt.Println("Impossible to send the reply:", err)
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
}

func main() {
	http.HandleFunc("/chatbot", bot)
	http.ListenAndServe(":5000", nil)
}

```

**Comment by ftriquet** [comment]
Where does your `CONNECTOR_TOKEN` comes from ?

**Comment by yageek** [comment]
I used the one provided on https://botconnector.recast.ai/me

**Comment by ftriquet** [comment]
Since we released the V2,  you only need the request token to use any APIs. You can find it on [recast.ai](https://recast.ai) in the settings of your bot. Bot Connector is now integrated in the platform.

**Comment by yageek** [comment]
By using the token on *recast.ai*, I have this error this time:
```Impossible to send the reply: Request failed (404 Not Found): Connector not found```

**Comment by ftriquet** [comment]
Does the bot have the same name as your connector? The migration should have created you a bot with the same name as your connector. If your bot on recast had a different name, I'm afraid you need to import your bot content in the new one or configure a connector on your bot on recast.

**Comment by yageek** [comment]
I just created a new one and I have the same issue.
I tested with the Node.JS sample (https://github.com/RecastAI/starter-NodeJS.git) and it succeeded to send a message. I still have the same error with Go.
